# Introduction to the Numerical Python (NumPy) library

# 1. What is Numpy and why do I care?
NumPy is the fundamental package for scientific computing with Python. It contains among other things:

* a powerful N-dimensional array object
* sophisticated (broadcasting) functions
* tools for integrating C/C++ and Fortran code
* useful linear algebra, Fourier transform, and random number capabilities

https://numpy.org/

### 2.1.2. Installation

Like any python package, you must have already downloaded and installed the package using your package manager. For vanilla python this would be done using pip and for Anaconda this would be done using conda.

In [3]:
! pip install numpy

# 3 Documentation and Usefull Links
The NumPy project hosts a quickstart tutorial which might be worth investigating:
https://numpy.org/devdocs/user/quickstart.html

This notebook will overlap with some (a very very very very very VERY small amount) of the concepts covered in the quickstart tutorial. It is worth reviewing at your own pace.

#### 4 The Basic NumPy Data Types
#### The multidimensional Array

NumPy’s main object is the homogeneous multidimensional (n-dimensional) array. The name of the class providing this functionality is the ndarray.

It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes.

Note that numpy.array is not the same as the Standard Python Library class array.array, which only handles one-dimensional arrays and offers less functionality. 

##### The class methods
**ndarray.ndim**

the number of axes (dimensions) of the array.

**ndarray.shape**

the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.

**ndarray.size**

the total number of elements of the array. This is equal to the product of the elements of shape.

**ndarray.dtype**

an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

**ndarray.itemsize**
the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.

**ndarray.data**

the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

# 5. Numpy Examples

In [4]:
# Import the numpy library into the current python session
import numpy

ModuleNotFoundError: No module named 'numpy'

In [3]:
# Create a three-by-five ndarray with random values 
three_by_five_ndarray = numpy.arange(15).reshape(3, 5)

# Show the value to the user
three_by_five_ndarray



NameError: name 'numpy' is not defined

In [6]:
# Explore some of the class methods as mentioned earlier
three_by_five_ndarray.ndim

2

In [5]:
three_by_five_ndarray.shape

(3, 5)

In [7]:
three_by_five_ndarray.dtype.name

'int64'

In [10]:
# Create a ndarray from the built in array
built_in_array = [1,2,3,4]
new_ndarray = numpy.array(built_in_array)
new_ndarray

array([1, 2, 3, 4])

In [16]:
# Create an ndarray where n > 2 using built in arrays
new_ndarray = numpy.array([(1,2,3,4), (5,6,7,8)])
new_ndarray


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
new_ndarray.shape

(2, 4)

In [20]:
# Access some data in the array
new_ndarray[0][0] * new_ndarray[1][3]


8

In [23]:
# Do some simple matrix algebra
m1 = numpy.array([(1, 2), (3, 4)])
print(m1)
print("")

m2 = numpy.array([(2, 2), (2, 2)])
print(m2)

m3 = m1 + m2
m3


[[1 2]
 [3 4]]

[[2 2]
 [2 2]]


array([[3, 4],
       [5, 6]])

In [44]:
# do some basic statistics on our data
print("The average of the array elements: {0}".format(m3.mean()))
print("The average of the 1st row: {0}".format(m3[0].mean()))
print("The average of the 2nd column: {0}".format(m3[:, 1].mean()))
print("The std deviation of the 2nd column: {0}".format(m3[:,1].std()))

The average of the array elements: 4.5
The average of the 1st row: 3.5
The average of the 2nd column: 5.0
The std deviation of the 2nd column: 1.0


# 6. Exercises