In [1]:
import numpy as np

In [2]:
b = [1,2,3,4]
b

[1, 2, 3, 4]

In [3]:
d = { "a" : 5, "b" : 6}
d

{'a': 5, 'b': 6}

In [5]:
n = np.array(b)
n

array([1, 2, 3, 4])

In [23]:
b2 = [[1,2,3,4],[5,6,7,8]]
n2 = np.array(b2)
type(n2[0][3])
n2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
type(5)

int

In [8]:
type((1, 2))

tuple

In [16]:
n2[1,:]

array([5, 6, 7, 8])

In [17]:
n2[1]

array([5, 6, 7, 8])

In [31]:
b1 = [1,2,3,4]
b2 = [5,6,7,8]
b3 = [9,10,11,12]
b4 = [b1, b2, b3]

n4 = np.array(b4)
n4.shape

(3, 4)

In [24]:
n2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
n4.ndim

2