# Overview
In this notebook we have a look at how to comute eigenvalues and eigenvectors using numpy (ie. do an eigen-decomposition or single value decomposition). We also look at some helpful proofs to show that the math is indeed correct.

This notebook assumes you already know spectral theory, single value decomposition, and or eigen-decomposition. If you are not familiar with these concepts refer to the material recomended in the [README](README.md).

We will be using the following formulas:

$$ Av = \lambda v $$
$$ A = U \Sigma V^T $$
$$ A = Q \Lambda Q^T $$

In [1]:
# Import the libraries we will be using
import numpy

# Example 1: Symetric Semi-definite positive matrix
We create an example matrix

In [2]:
A = numpy.array([[1,2,3],
                 [2,2,1],
                 [3,1,1]])
print(A)

[[1 2 3]
 [2 2 1]
 [3 1 1]]


We then do the decomposition using numpy.

In [3]:
lam, v = numpy.linalg.eig(A)
print(lam)
print("")
print(v)

[ 5.36488085 -2.14644241  0.78156156]

[[-0.63053714 -0.74009445  0.23384422]
 [-0.54035845  0.20230251 -0.81675359]
 [-0.55716753  0.64135318  0.52747554]]


## Decomposition Proof
We can look at proving $ Av = \lambda v $

### Go vector by vector
We can first look at multiplying each column of the right eigenvector $v$ by the coresponding scalar eigenvalue $\lambda$.

In [4]:
# Case 0
print(numpy.dot(A,v[:, 0]))
print("")
print(numpy.dot(lam[0], v[:, 0]))

[-3.38275663 -2.89895872 -2.98913741]

[-3.38275663 -2.89895872 -2.98913741]


In [5]:
# Case 1
print(numpy.dot(A,v[:, 1]))
print("")
print(numpy.dot(lam[1], v[:, 1]))

[ 1.58857011 -0.43423069 -1.37662766]

[ 1.58857011 -0.43423069 -1.37662766]


In [6]:
# Case 2
print(numpy.dot(A,v[:, 2]))
print("")
print(numpy.dot(lam[2], v[:, 2]))

[ 0.18276365 -0.63834321  0.4122546 ]

[ 0.18276365 -0.63834321  0.4122546 ]


### Do everything using matrix algebra
Using matrix algebra we would can multiply the set of scalars $\lambda$ by the matrix $v$:

In [7]:
# General Case
#    Using scalar multiplication
print(numpy.matmul(A, v))
print("")
print(lam * v)

[[-3.38275663  1.58857011  0.18276365]
 [-2.89895872 -0.43423069 -0.63834321]
 [-2.98913741 -1.37662766  0.4122546 ]]

[[-3.38275663  1.58857011  0.18276365]
 [-2.89895872 -0.43423069 -0.63834321]
 [-2.98913741 -1.37662766  0.4122546 ]]


We can convert the set of scalars $\lambda$ back into the matrix $\Lambda$ by multiplying by the identity matrix $I$. We will see the equation is slightly different if we are consious of matrix dimensions:

$$ Av = (\Lambda v^T)^T $$

In [8]:
Lam = lam * numpy.identity(3)
print(Lam)

[[ 5.36488085 -0.          0.        ]
 [ 0.         -2.14644241  0.        ]
 [ 0.         -0.          0.78156156]]


In [9]:
# General Case
#    Using matmul to perform matrix multiplication
print(numpy.matmul(A, v))
print("")
print(numpy.matmul(Lam, v.T).T)

[[-3.38275663  1.58857011  0.18276365]
 [-2.89895872 -0.43423069 -0.63834321]
 [-2.98913741 -1.37662766  0.4122546 ]]

[[-3.38275663  1.58857011  0.18276365]
 [-2.89895872 -0.43423069 -0.63834321]
 [-2.98913741 -1.37662766  0.4122546 ]]


## Orthogonal Proof
Here we can show that the matrix $v$ is orthoganal such that:

$$ v \perp v^T := vv^t=I = vv^{-1} $$

In [10]:
numpy.matmul(v, v.T).round()

array([[ 1., -0., -0.],
       [-0.,  1.,  0.],
       [-0.,  0.,  1.]])

In [11]:
numpy.array_equal(numpy.matmul(v, v.T).round(),  numpy.identity(3))

True

In [12]:
numpy.array_equal(numpy.matmul(v, numpy.linalg.inv(v)).round(),  numpy.identity(3))

True

## Recompose the original matrix
Here we will show that we can recreate the original matrix thus proving $A = Q \Lambda Q^T$.

In [13]:
print(A)

[[1 2 3]
 [2 2 1]
 [3 1 1]]


In [14]:
Q = v
print(Q)

[[-0.63053714 -0.74009445  0.23384422]
 [-0.54035845  0.20230251 -0.81675359]
 [-0.55716753  0.64135318  0.52747554]]


In [15]:
Qt = numpy.linalg.inv(Q)
print(Qt)

[[-0.63053714 -0.54035845 -0.55716753]
 [-0.74009445  0.20230251  0.64135318]
 [ 0.23384422 -0.81675359  0.52747554]]


In [16]:
Lam = numpy.diag(lam)

In [17]:
A_rec = Q @ Lam @ Qt
print(A_rec)

[[1. 2. 3.]
 [2. 2. 1.]
 [3. 1. 1.]]


**Note:** The @ symbol was introduced in 2016 as an alias for numpy.matmul() function. As we can see, it is much more convenient:

In [18]:
print(numpy.matmul(numpy.matmul(Q, Lam), Qt))

[[1. 2. 3.]
 [2. 2. 1.]
 [3. 1. 1.]]
